name: Automerge PRs
on:
  pull_request_target:
    branches: [ main ]
    types: [ opened ]
  push:
    branches-ignore:
      - 'main'

permissions:
  pull-requests: write
  contents: write

jobs:
  autoMerge:
    runs-on: ubuntu-latest
    if: github.event.pull_request.user.login == 'dependabot[bot]'
    steps:
      - uses: actions/checkout@v3
      - run: gh pr merge -r "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}